include:
  - ${ROOT_DIRECTORY}/docker/nginx-proxy/docker-compose.yml
  - ${ROOT_DIRECTORY}/docker/apache/docker-compose.yml
  - ${ROOT_DIRECTORY}/docker/mysql/docker-compose.yml
  - ${ROOT_DIRECTORY}/docker/php-fpm/docker-compose.yml
  - ${ROOT_DIRECTORY}/docker/pma/docker-compose.yml
  - ${ROOT_DIRECTORY}/docker/mailpit/docker-compose.yml
  - ${ROOT_DIRECTORY}/docker/php-phpstan/docker-compose.yml
  - ${ROOT_DIRECTORY}/docker/php-cs/docker-compose.yml
  - ${ROOT_DIRECTORY}/docker/php-doctrine-migrations/docker-compose.yml

#  - ${ROOT_DIRECTORY}/docker/mariadb/docker-compose.yml
#  - ${ROOT_DIRECTORY}/docker/nginx/docker-compose.yml

networks:
  network_app:
    driver: bridge
    name: ${PROJECT_NAME}-${ENV}-network
