global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']

  #Database monitoring
#  - job_name: 'mysqld-exporter'
#    static_configs:
#      - targets: ['mysqld-exporter:9104']

  #App monitoring
  - job_name: 'nginx exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nginx-exporter:9113']

  #App monitoring
  - job_name: 'php-fpm exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['php-fpm-exporter:9253']

  #Server and Docker instances monitoring
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  #Server and Docker instances monitoring
  - job_name: 'crontab exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'pagespeed exporter'
    scrape_interval: 60m
    metrics_path: /probe
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: "page-speed-exporter:9271"
    static_configs:
      - targets:
          - 'https://gameroom.lt/lt/'
#          - '{"url":"http://gameroom.local/","campaign":"test","locale":"en","source":"source"}'
#          - '{"url":"http://gameroom.local/","strategy":"mobile"}'
